apiVersion: batch/v1
kind: CronJob
metadata:
    name: energy-loader
spec:
    schedule: "0 * * * *"
    jobTemplate:
        spec:
            backoffLimit: 3
            template:
                spec:
                    restartPolicy: OnFailure
                    containers:
                        - name: energy-loader
                          image: francescorisso/domoticocasa-energia:latest
                          resources:
                              limits:
                                  memory: "500Mi"
                                  cpu: "500m"
