apiVersion: batch/v1
kind: CronJob
metadata:
    name: temperature-loader
spec:
    schedule: "*/5 * * * *"
    concurrencyPolicy: Replace
    jobTemplate:
        spec:
            backoffLimit: 3
            template:
                spec:
                    restartPolicy: OnFailure
                    containers:
                        - name: temperature-loader
                          image: francescorisso/domoticocasa-temperatura:latest
                          resources:
                              limits:
                                  memory: "250Mi"
                                  cpu: "250m"
