name: build docker containers and push to Dockerhub

on:
    push:
        branches: ["master"]

jobs:
    temperatura:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
              with:
                  ref: build

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Temperatura.Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/domoticocasa-temperatura:latest

    energia:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
              with:
                  ref: build

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Energia.Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/domoticocasa-energia:latest
